# AUTOGENERATED! DO NOT EDIT! File to edit: ../../scripts/_mkl/notebooks/06b - Gaussian Sensor Model.ipynb.

# %% auto 0
__all__ = ["normal_cdf", "normal_pdf", "normal_logpdf", "inv", "key"]

# %% ../../scripts/_mkl/notebooks/06b - Gaussian Sensor Model.ipynb 3
import jax
import jax.numpy as jnp

# %% ../../scripts/_mkl/notebooks/06b - Gaussian Sensor Model.ipynb 4
from bayes3d._mkl.types import *
from bayes3d._mkl.utils import *

# %% ../../scripts/_mkl/notebooks/06b - Gaussian Sensor Model.ipynb 5
normal_cdf = jax.scipy.stats.norm.cdf
normal_pdf = jax.scipy.stats.norm.pdf
normal_logpdf = jax.scipy.stats.norm.logpdf
inv = jnp.linalg.inv

key = jax.random.PRNGKey(0)
