# AUTOGENERATED! DO NOT EDIT! File to edit: ../../scripts/_mkl/notebooks/06b - Gaussian Sensor Model.ipynb.

# %% auto 0
__all__ = ['normal_cdf', 'normal_pdf', 'normal_logpdf', 'inv', 'key']

# %% ../../scripts/_mkl/notebooks/06b - Gaussian Sensor Model.ipynb 3
import bayes3d as b3d
import trimesh
import os
from bayes3d._mkl.utils import *
import matplotlib.pyplot as plt
import numpy as np
import jax
from jax import jit, vmap
import jax.numpy as jnp
from functools import partial
from bayes3d.camera import Intrinsics, K_from_intrinsics, camera_rays_from_intrinsics
from bayes3d.transforms_3d import transform_from_pos_target_up, add_homogenous_ones, unproject_depth
import tensorflow_probability as tfp
from tensorflow_probability.substrates.jax.math import lambertw


# %% ../../scripts/_mkl/notebooks/06b - Gaussian Sensor Model.ipynb 4
from bayes3d._mkl.types import *
from bayes3d._mkl.gaussian_renderer import (
    weighted_arrival_intersection, 
    weighted_argmax_intersection,
    discrete_arrival_probabilities
)


# %% ../../scripts/_mkl/notebooks/06b - Gaussian Sensor Model.ipynb 5
normal_cdf    = jax.scipy.stats.norm.cdf
normal_pdf    = jax.scipy.stats.norm.pdf
normal_logpdf = jax.scipy.stats.norm.logpdf
inv = jnp.linalg.inv

key = jax.random.PRNGKey(0)
