# AUTOGENERATED! DO NOT EDIT! File to edit: ../../scripts/_mkl/notebooks/07a - Gaussian particle system v0.ipynb.

# %% auto 0
__all__ = [
    "normal_cdf",
    "normal_pdf",
    "normal_logpdf",
    "inv",
    "key",
    "Array",
    "Shape",
    "Bool",
    "Float",
    "Int",
    "Pose",
]

# %% ../../scripts/_mkl/notebooks/07a - Gaussian particle system v0.ipynb 2
import jax
import jax.numpy as jnp
import numpy as np

from bayes3d._mkl.utils import *

normal_cdf = jax.scipy.stats.norm.cdf
normal_pdf = jax.scipy.stats.norm.pdf
normal_logpdf = jax.scipy.stats.norm.logpdf
inv = jnp.linalg.inv

key = jax.random.PRNGKey(0)

# %% ../../scripts/_mkl/notebooks/07a - Gaussian particle system v0.ipynb 4
from typing import NamedTuple

import jax
import numpy as np

Array = np.ndarray | jax.Array
Shape = int | tuple[int, ...]
Bool = Array
Float = Array
Int = Array

Pose = tuple[jnp.ndarray, jnp.ndarray]


class Pose(NamedTuple):
    quat: jnp.ndarray
    position: jnp.ndarray
